version: '3.6'

services:
#  origin:
#    image: airensoft/ovenmediaengine:0.16.0
##    build:
##      context: ./OvenMediaEngine/
##      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#    - "1935:1935/tcp" # RTMP Provider
#    - "8945:8945/tcp" # TLS Management
#    - "9000:9000/tcp" # OVT(Origin)
#    - "9999:9999/udp" # SRT Provider
#    environment:
#    - OME_RTMP_PROV_PORT=1935
#    - TLS_API_PORT=8945
#    - OVT_ORIGIN_PORT=9000
#    - OME_SRT_PROV_PORT=9999
#    - TLS_DOMAIN_NAME=sinkx.example.com
#    - CPU_CORES_COUNT=6
#    - OME_ACCESS_TOKEN=ome-access-token
#    - ALERT_WEBHOOK_URL=https://yourAlertWebhook.tld/path
#    - ALERT_WEBHOOK_SECRET=alert-hook-secret
#    - ADMISSION_WEBHOOK_URL=admissionwekhookurl
#    - ADMISSION_WEBHOOK_SECRET=admission-hook-secret
#    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
#    volumes:
#    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
#    - ./tls:/etc/ssl
#    stop_signal: KILL

  edge:
    image: airensoft/ovenmediaengine:0.16.0
#    build:
#      context: ./OvenMediaEngine/
#      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "80:80/tcp" # HTTP 1.2 HLS
    - "443:443/tcp" # HTTP 2 LLHLS
    - "3334:3334/tcp" # WebRTC Signalling
    - "3479:3479/tcp" # WebRTC TURN
    - "8944:8944/tcp" # TLS API
    - "9001:9001/tcp" # OVT Edge Port
    - "10000-10005:10000-10005/udp" # WebRTC Candidate
    environment:
    - TLS_HTTP_PORT=443
    - OME_SIGNALLING_PORT=3334
    - OME_TCP_RELAY_ADDRESS=123.123.123.123:3479
    - TLS_API_PORT=8944
    - OVT_ORIGIN_PORT=9000
    - OME_ICE_CANDIDATES=123.123.123.123:10000-10005/udp
    - OVT_ORIGIN_SERVER=sink1.example.com
    - TLS_DOMAIN_NAME=oven.example.com
    - CPU_CORES_COUNT=4
    - OME_ACCESS_TOKEN=ome-access-token
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
    volumes:
    - ./edge_conf:/opt/ovenmediaengine/bin/edge_conf
    - ./tls:/etc/ssl
    stop_signal: KILL
